### ISSUE TITLE
picamserver from ICE to ROS2

### ISSUE THREAD

**Issue by pankhurivanjani** [JdeRobot/ros2-drivers#3]
Current installation on ICE : [https://github.com/JdeRobot/base/tree/master/src/drivers/picamserver](link)
I am starting to develop picamserver to ROS2. Is it a good idea to start it or some other driver should be given priority?

**Comment by jmplaza** [comment]
picamserver works specifically on RaspberryPi, maybe it is not so important to migrate it to ROS2. Better we could focus on supporting [TurtleBot2 robot](https://github.com/ros2/turtlebot2_demo) (if you have access to one of them) or on supporting a TurtleBot2 robot simulated in Gazebo, using ROS2.

For instance we should update some of the JdeRobot visualization tools (like [carViz](https://github.com/JdeRobot/base/tree/master/src/tools/carViz)) to support its connection to ROS1 simulated TurtleBot2 in Gazebo and ROS2 simulated TurtleBot2 in Gazebo.

**Comment by pankhurivanjani** [comment]
Hi, @jmplaza I have access to Raspberry pi but not Turtlebot so I can work on gazebo simulation. 

Also as you suggested we should update some of the tools of JDEROBOT (like visualization -carViz)  I would like to start working in it. Since this repository is for ros2-drivers can we have another repository for ros2-tools?

**Comment by jmplaza** [comment]
We are in the process of moving all the visualization tools to the [JdeRobot/Viz](https://github.com/JdeRobot/viz) repository. For instance the [camviz from JdeRobot/base](https://github.com/JdeRobot/base/tree/master/src/tools/carViz) 

 Maybe we could just create there, at JdeRobot/viz, a new carViz-ros2 tool hopefully to be integrated with carViz there, so the future carviz will be compatible both with ros1 and ros2.

What do you think @pankhurivanjani ?

**Comment by pankhurivanjani** [comment]
That would be a good idea when we are considering visualization tools. 
Since we have other tools like visualstates [Visualstates](https://github.com/JdeRobot/VisualStates)  which we are aiming to work with ROS2 drivers so we have to create a new tool for ros2 there also?

**Comment by jmplaza** [comment]
better one by one. And carViz is a nice and not-too-complex tool to start with.
